# Generated by Django 3.0.7 on 2020-06-23 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField(default=True)),
                ('roast', models.BooleanField(default=True)),
                ('up_votes', models.IntegerField()),
                ('down_votes', models.IntegerField()),
                ('submission', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
