# Generated by Django 3.0.7 on 2020-06-23 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ghostpost',
            old_name='boast',
            new_name='is_boast',
        ),
        migrations.RemoveField(
            model_name='ghostpost',
            name='roast',
        ),
        migrations.AddField(
            model_name='ghostpost',
            name='post',
            field=models.CharField(default='test', max_length=280),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='submission',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
