# Generated by Django 3.0.7 on 2020-06-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost_app', '0002_auto_20200623_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='is_boast',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
